/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sowan.gui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.Security;
import sowan.objects.Karyawan;
import sowan.services.KaryawanService;
import sowan.services.bahasaService;
import javax.swing.SwingUtilities;
import koneksi.EncryptionUtils;
import sowan.objects.ComboItem;
/**
 *
 * @author SUWONO
 */
public class FormEditKaryawan extends javax.swing.JFrame {
    
    public FormEditKaryawan(){
        initComponents();
        renderLang(); // Tambahkan baris ini
    }
    
    private JPanel targetDashboard;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormEditKaryawan.class.getName());

    /**
     * Creates new form FormEditKaryawan
     * @param targetDashboard
     */
    public FormEditKaryawan(JPanel targetDashboard) {
        this.setUndecorated(true);
        initComponents();
        this.targetDashboard = targetDashboard;
        
        renderLang(); // Tambahkan baris ini
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NIP_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Departemen_lbl = new javax.swing.JLabel();
        jabatan_lbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id_karyawan = new javax.swing.JTextField();
        rfid_uid = new javax.swing.JTextField();
        nama_lengkap = new javax.swing.JTextField();
        cmbdepartemen = new javax.swing.JComboBox<>();
        cmbjabatan = new javax.swing.JComboBox<>();
        cmbshift = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        NIP_lbl.setText("NIP");

        jLabel3.setText("Nama");

        Departemen_lbl.setText("Departemen");

        jabatan_lbl.setText("Jabatan");

        jLabel6.setText("Shift");

        id_karyawan.setText("ID");
        id_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_karyawanActionPerformed(evt);
            }
        });

        rfid_uid.setText("rfid_uid");
        rfid_uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfid_uidActionPerformed(evt);
            }
        });

        nama_lengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_lengkapActionPerformed(evt);
            }
        });

        cmbdepartemen.setModel(new javax.swing.DefaultComboBoxModel<sowan.objects.ComboItem>());
        cmbdepartemen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbdepartemenItemStateChanged(evt);
            }
        });
        cmbdepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdepartemenActionPerformed(evt);
            }
        });

        cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel<sowan.objects.ComboItem>());
        cmbjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjabatanActionPerformed(evt);
            }
        });

        cmbshift.setModel(new javax.swing.DefaultComboBoxModel<sowan.objects.ComboItem>());

        btnSimpan.setBackground(new java.awt.Color(0, 51, 153));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel1.setText("EDIT KARYAWAN");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(NIP_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbdepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Departemen_lbl)
                                        .addComponent(jabatan_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama_lengkap)
                                    .addComponent(cmbshift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rfid_uid, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NIP_lbl))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nama_lengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)
                        .addGap(63, 63, 63)
                        .addComponent(rfid_uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Departemen_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbdepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbshift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jabatan_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbdepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdepartemenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdepartemenActionPerformed

    private void nama_lengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_lengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_lengkapActionPerformed

    private void rfid_uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfid_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfid_uidActionPerformed

    private void id_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_karyawanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            // 1. Validasi ComboBox agar tidak error jika kosong
            if (cmbdepartemen.getSelectedItem() == null || 
                cmbjabatan.getSelectedItem() == null || 
                cmbshift.getSelectedItem() == null) {
                
                javax.swing.JOptionPane.showMessageDialog(this, "Harap pilih Departemen, Jabatan, dan Shift dengan benar!");
                return;
            }

            Karyawan K = new Karyawan();

            // 2. Set Data Teks & Enkripsi
            K.setId_karyawan(koneksi.Encryption.encrypt(id_karyawan.getText()));
            K.setRfid_uid(koneksi.Security.getHash(rfid_uid.getText(), koneksi.Security.SHA_256));
            K.setNama_lengkap(nama_lengkap.getText());

            // 3. INI BAGIAN YANG DIPERBAIKI: Ambil KEY dari ComboItem
            ComboItem itemDept = (ComboItem) cmbdepartemen.getSelectedItem();
            ComboItem itemJabatan = (ComboItem) cmbjabatan.getSelectedItem();
            ComboItem itemShift = (ComboItem) cmbshift.getSelectedItem();

            K.setDepartemen(itemDept.getKey());
            K.setJabatan(itemJabatan.getKey());
            K.setShift(itemShift.getKey());

            // 4. Proses Update ke Database
            KaryawanService service = new KaryawanService();
            service.updateKaryawan(K, targetDashboard);

            // Tutup form setelah berhasil
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, bahasaService.get("msg_update_gagal") + " " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cmbjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjabatanActionPerformed

    private void cmbdepartemenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbdepartemenItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdepartemenItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Departemen_lbl;
    private javax.swing.JLabel NIP_lbl;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    public javax.swing.JComboBox<ComboItem> cmbdepartemen;
    public javax.swing.JComboBox<ComboItem> cmbjabatan;
    public javax.swing.JComboBox<ComboItem> cmbshift;
    public javax.swing.JTextField id_karyawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jabatan_lbl;
    public javax.swing.JTextField nama_lengkap;
    public javax.swing.JTextField rfid_uid;
    // End of variables declaration//GEN-END:variables
        // Fungsi pembantu untuk memilih ComboBox berdasarkan Key Database
    public void setComboSelectionByKey(javax.swing.JComboBox combo, String key) {
        if (key == null) return;
        for (int i = 0; i < combo.getItemCount(); i++) {
            ComboItem item = (ComboItem) combo.getItemAt(i);
            if (item.getKey().equals(key)) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void renderLang() {
        SwingUtilities.invokeLater(() -> {
            // --- UPDATE LABEL & BUTTON ---
            jLabel1.setText(bahasaService.get("edit_karyawan_title")); // Judul Form
            NIP_lbl.setText(bahasaService.get("label_id"));
            jLabel3.setText(bahasaService.get("label_nama")); // Karena Anda menggunakan jLabel3 untuk Nama
            Departemen_lbl.setText(bahasaService.get("label_dept"));
            jabatan_lbl.setText(bahasaService.get("label_jabatan"));
            jLabel6.setText(bahasaService.get("label_shift"));

            btnSimpan.setText(bahasaService.get("btn_simpan"));
            btnBatal.setText(bahasaService.get("btn_batal"));

            // --- UPDATE COMBOBOX ---
            // 1. Simpan Kunci (Key) dari pilihan saat ini (jika ada) agar tidak reset saat ganti bahasa
            String selectedDeptKey = (cmbdepartemen.getSelectedItem() != null) ? ((ComboItem) cmbdepartemen.getSelectedItem()).getKey() : null;
            String selectedJabatanKey = (cmbjabatan.getSelectedItem() != null) ? ((ComboItem) cmbjabatan.getSelectedItem()).getKey() : null;
            String selectedShiftKey = (cmbshift.getSelectedItem() != null) ? ((ComboItem) cmbshift.getSelectedItem()).getKey() : null;
            
            // 2. Isi ComboBox dengan objek ComboItem (Key, Terjemahan)
            cmbdepartemen.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] { 
                new ComboItem("dept_keuangan", bahasaService.get("dept_keuangan")), 
                new ComboItem("dept_marketing", bahasaService.get("dept_marketing")), 
                new ComboItem("dept_it", bahasaService.get("dept_it")), 
                new ComboItem("dept_ops", bahasaService.get("dept_ops")) 
            }));
            
            cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] { 
                new ComboItem("jabatan_manager", bahasaService.get("jabatan_manager")), 
                new ComboItem("jabatan_staf", bahasaService.get("jabatan_staf")), 
                new ComboItem("jabatan_spv", bahasaService.get("jabatan_spv")) 
            }));
            
            cmbshift.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] { 
                new ComboItem("shift_pagi", bahasaService.get("shift_pagi")), 
                new ComboItem("shift_malam", bahasaService.get("shift_malam")) 
            }));
            
            // 3. Kembalikan pilihan berdasarkan KEY-nya
            setComboSelectionByKey(cmbdepartemen, selectedDeptKey);
            setComboSelectionByKey(cmbjabatan, selectedJabatanKey);
            setComboSelectionByKey(cmbshift, selectedShiftKey);
        });
    }
        
}
