package sowan.gui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sowan.services.KaryawanService;
import sowan.objects.Karyawan;
import koneksi.Security;
import koneksi.Encryption;
import sowan.services.bahasaService; // Tambahkan import bahasaService
import javax.swing.SwingUtilities;
import sowan.objects.ComboItem;

/**
 *
 * @author SUWONO
 */
public class FormTambahKaryawan extends javax.swing.JFrame {
    private JPanel targetDashboard;
    private DashboardPage mainFrame;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahKaryawan.class.getName());
    
    public FormTambahKaryawan(DashboardPage mainFrame, JPanel panelTarget) {
        initComponents();
        this.mainFrame = mainFrame;
        this.targetDashboard = panelTarget;
        renderLang(); // <-- TAMBAHKAN INI
    }

    /**
     * Creates new form FormKarywan
     * @param targetDashboard
     */
    public FormTambahKaryawan(JPanel targetDashboard) {
        initComponents();
        this.targetDashboard = targetDashboard;
        
        renderLang(); // Tambahkan baris ini
    }

    // --- TAMBAHKAN METHOD renderLang() DI SINI ---
    // Fungsi untuk memilih item ComboBox berdasarkan Key
    public void setComboSelectionByKey(javax.swing.JComboBox combo, String key) {
        if (key == null) return;
        for (int i = 0; i < combo.getItemCount(); i++) {
            ComboItem item = (ComboItem) combo.getItemAt(i);
            if (item.getKey().equals(key)) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }

    // Fungsi untuk mengubah semua teks sesuai bahasa
    private void renderLang() {
        SwingUtilities.invokeLater(() -> {
            // Update Label & Button
            lbltambahkaryawan.setText(bahasaService.get("tambah_karyawan_title"));
            NIP_lbl.setText(bahasaService.get("label_id")); 
            nama_lbl.setText(bahasaService.get("label_nama"));
            jLabel2.setText(bahasaService.get("label_dept"));
            jLabel3.setText(bahasaService.get("label_jabatan"));
            jLabel4.setText(bahasaService.get("label_shift"));
            
            btnSimpan.setText(bahasaService.get("btn_simpan"));
            btnBatal.setText(bahasaService.get("btn_batal"));
            
            // Simpan index saat ini
            String selectedDeptKey = (cmbdepartemen.getSelectedItem() != null) ? ((ComboItem) cmbdepartemen.getSelectedItem()).getKey() : null;
            String selectedJabatanKey = (cmbjabatan.getSelectedItem() != null) ? ((ComboItem) cmbjabatan.getSelectedItem()).getKey() : null;
            String selectedShiftKey = (cmbshift.getSelectedItem() != null) ? ((ComboItem) cmbshift.getSelectedItem()).getKey() : null;
            
            // Isi ComboBox dengan ComboItem (Key, Value)
            cmbdepartemen.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] { 
                new ComboItem("dept_keuangan", bahasaService.get("dept_keuangan")), 
                new ComboItem("dept_marketing", bahasaService.get("dept_marketing")), 
                new ComboItem("dept_it", bahasaService.get("dept_it")), 
                new ComboItem("dept_ops", bahasaService.get("dept_ops")) 
            }));
            
            cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] { 
                new ComboItem("jabatan_manager", bahasaService.get("jabatan_manager")), 
                new ComboItem("jabatan_staf", bahasaService.get("jabatan_staf")), 
                new ComboItem("jabatan_spv", bahasaService.get("jabatan_spv")) 
            }));
            
            cmbshift.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] { 
                new ComboItem("shift_pagi", bahasaService.get("shift_pagi")), 
                new ComboItem("shift_malam", bahasaService.get("shift_malam")) 
            }));
            
            // Kembalikan pilihan
            setComboSelectionByKey(cmbdepartemen, selectedDeptKey);
            setComboSelectionByKey(cmbjabatan, selectedJabatanKey);
            setComboSelectionByKey(cmbshift, selectedShiftKey);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        cmbshift = new javax.swing.JComboBox<>();
        cmbjabatan = new javax.swing.JComboBox<>();
        lbltambahkaryawan = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        nama_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid_karyawan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtrfid_uid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnama_lengkap = new javax.swing.JTextField();
        NIP_lbl = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        cmbdepartemen = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        cmbshift.setModel(new javax.swing.DefaultComboBoxModel<sowan.objects.ComboItem>());

        cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel<sowan.objects.ComboItem>());
        cmbjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjabatanActionPerformed(evt);
            }
        });

        lbltambahkaryawan.setText("TAMBAH KARYAWAN");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        nama_lbl.setText("Nama ");

        jLabel2.setText("Departemen");

        txtid_karyawan.setText("ID");
        txtid_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_karyawanActionPerformed(evt);
            }
        });

        jLabel3.setText("Jabatan");

        txtrfid_uid.setText("rfid_uid");
        txtrfid_uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrfid_uidActionPerformed(evt);
            }
        });

        jLabel4.setText("Shift");

        txtnama_lengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama_lengkapActionPerformed(evt);
            }
        });

        NIP_lbl.setText("NIP");

        btnSimpan.setBackground(new java.awt.Color(0, 51, 204));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        cmbdepartemen.setModel(new javax.swing.DefaultComboBoxModel<sowan.objects.ComboItem>());
        cmbdepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdepartemenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbdepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NIP_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtid_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cmbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmbshift, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnama_lengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nama_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtrfid_uid, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lbltambahkaryawan)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbltambahkaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIP_lbl)
                    .addComponent(nama_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama_lengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbshift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbdepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtrfid_uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnBatal)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cmbdepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdepartemenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdepartemenActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            // 1. Validasi apakah ComboBox sudah dipilih dengan benar
            if (cmbdepartemen.getSelectedItem() == null || 
                cmbjabatan.getSelectedItem() == null || 
                cmbshift.getSelectedItem() == null) {
                
                javax.swing.JOptionPane.showMessageDialog(this, "Harap pilih Departemen, Jabatan, dan Shift terlebih dahulu!");
                return; // Hentikan proses simpan
            }

            Karyawan K = new Karyawan();
            
            K.setId_karyawan(koneksi.Encryption.encrypt(txtid_karyawan.getText()));
            K.setRfid_uid(koneksi.Security.getHash(txtrfid_uid.getText(), koneksi.Security.SHA_256));
            K.setNama_lengkap(txtnama_lengkap.getText());
            
            // 2. Ambil Key dari ComboBox
            ComboItem itemDept = (ComboItem) cmbdepartemen.getSelectedItem();
            ComboItem itemJabatan = (ComboItem) cmbjabatan.getSelectedItem();
            ComboItem itemShift = (ComboItem) cmbshift.getSelectedItem();

            K.setDepartemen(itemDept.getKey());
            K.setJabatan(itemJabatan.getKey());
            K.setShift(itemShift.getKey());
            
            // 3. Simpan
            sowan.services.KaryawanService service = new sowan.services.KaryawanService();
            service.tambahKaryawan(K);

            javax.swing.JOptionPane.showMessageDialog(this, sowan.services.bahasaService.get("msg_simpan_sukses"));
            
            service.tampilKaryawan(targetDashboard, "");
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, sowan.services.bahasaService.get("msg_simpan_gagal") + " " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtnama_lengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama_lengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama_lengkapActionPerformed

    private void txtrfid_uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrfid_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrfid_uidActionPerformed

    private void txtid_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_karyawanActionPerformed

    private void cmbjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjabatanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NIP_lbl;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<ComboItem> cmbdepartemen;
    private javax.swing.JComboBox<ComboItem> cmbjabatan;
    private javax.swing.JComboBox<ComboItem> cmbshift;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbltambahkaryawan;
    private javax.swing.JLabel nama_lbl;
    private javax.swing.JTextField txtid_karyawan;
    private javax.swing.JTextField txtnama_lengkap;
    private javax.swing.JTextField txtrfid_uid;
    // End of variables declaration//GEN-END:variables

}

